name: Build and Release

on:
  push:
    tags:
      - 'v*' # This triggers the workflow only on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: goto-bus-stop/setup-zig@v2    
    - name: Build the project
      run: zig build -O ReleaseSafe# Replace with your build comman
